# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{
  pkgs,
  fetchurl,
  fetchgit,
  fetchhg,
}:

self: super: {
  "proces" = super.buildPythonPackage rec {
    pname = "proces";
    version = "0.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8a/e9/76b96cdd7646ea2bc2087dce29bcc64b0c64b019583486fdc41378f7691c/proces-0.1.2-py3-none-any.whl";
      sha256 = "1lqgrpp0gwvb287ikiynk0yfrg031mqig5hm0fp0lydy1v3nbdw2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      pkgs.python312Packages.setuptools
      self."zhconv"
    ];
  };
  "zhconv" = super.buildPythonPackage rec {
    pname = "zhconv";
    version = "1.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/47/c8ae2d5d4025e253211ff3d8c163f457db1da94976cb582337a5ab76cb87/zhconv-1.4.3.tar.gz";
      sha256 = "0iccd6r5j565c82q9riy35c9z1vzg756fayn8675yq50gh2xjhmd";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
}
