name: CI

on: [push, pull_request]

jobs:
  test_generate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: setup python env
      run: pip install -r requirements.txt
    - name: generate tex
      run: python generate-tex.py > tex/eclab-beamer.tex
    - name: build pdf
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: tex
        root_file: eclab-beamer.tex
        latexmk_use_xelatex: true
